sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

services:
- docker

cache:
  directories:
  - $HOME/.m2/repository

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: unit test and crossdock
      script: ./mvnw test
    - script: make crossdock-fresh

branches:
  except:
    - /^[0-9]/
